# ========================
# BASIC
# ========================
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, Q, killactive
bind = $mainMod, M, exit

# ========================
# APPS
# ========================
bind = $mainMod, B, exec, $browser
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, C, exec, $editor
bind = $mainMod, Space, exec, $menu

# fallback launcher
bind = $mainMod, D, exec, rofi -show drun

# ========================
# MOVE FOCUS
# ========================
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# ========================
# MOVE WINDOWS
# ========================
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d

# ========================
# WORKSPACES
# ========================
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# scroll workspaces
bind = $mainMod, mouse_up, workspace, e+1
bind = $mainMod, mouse_down, workspace, e-1

# ========================
# WINDOW CONTROL
# ========================
bind = $mainMod, F, fullscreen
bind = $mainMod SHIFT, F, togglefloating
bind = $mainMod, P, pin

# ========================
# RESIZE
# ========================
binde = $mainMod CTRL, right, resizeactive, 40 0
binde = $mainMod CTRL, left, resizeactive, -40 0
binde = $mainMod CTRL, up, resizeactive, 0 -40
binde = $mainMod CTRL, down, resizeactive, 0 40

# ========================
# UTIL
# ========================
bind = $mainMod SHIFT, R, exec, hyprctl reload

# screenshots
bind = , Print, exec, grimblast --notify copysave screen
bind = SUPER SHIFT, S, exec, grimblast --notify copysave area

# lock/logout
bind = SUPER, L, exec, hyprlock
bind = SUPER, ESCAPE, exec, wlogout

# ========================
# MOUSE
# ========================
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
