# ========================
# MONITOR
# ========================
monitor=,preferred,auto,1

# ========================
# INPUT
# ========================
input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        natural_scroll = true
    }
}

gestures {
	gesture = 3, horizontal, workspace
}

# ========================
# GENERAL
# ========================
general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgb(7aa2f7)
    col.inactive_border = rgb(2e3440)

    resize_on_border = true
    layout = dwindle
}

# ========================
# VARIABLES
# ========================
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$browser = brave-browser
$editor = code
$menu = rofi -show drun

# ========================
# ENV
# ========================
env = QT_QPA_PLATFORM,wayland
env = GDK_BACKEND,wayland,x11,*
env = SDL_VIDEODRIVER,wayland
env = XDG_CURRENT_DESKTOP,Hyprland

# ========================
# SOURCE FILES
# ========================
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/autostart.conf
exec-once = hyprpaper -c ~/.config/hypr/hyprpaper.conf
exec-once = hypridle
